# Generated by Django 4.2.23 on 2025-07-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_finalize_prodejna_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_zakaznika', models.CharField(max_length=100, verbose_name='Jméno zákazníka')),
                ('prijmeni_zakaznika', models.CharField(max_length=100, verbose_name='Příjmení zákazníka')),
                ('telefon_zakaznika', models.CharField(max_length=20, verbose_name='Telefon zákazníka')),
                ('typ_telefonu', models.CharField(max_length=100, verbose_name='Typ telefonu')),
                ('dil', models.CharField(max_length=100, verbose_name='Díl')),
                ('barva', models.CharField(blank=True, max_length=50, null=True, verbose_name='Barva')),
                ('status', models.CharField(choices=[('nove', 'Nové'), ('objednano', 'Objednáno'), ('v_kosiku', 'V košíku'), ('predobjednano', 'Předobjednáno'), ('neni_skladem', 'Není skladem'), ('storno', 'Storno'), ('dorazilo_ceka', 'Dorazilo čeká na zákazníka'), ('hotovo', 'Hotovo')], default='nove', max_length=20, verbose_name='Stav')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('datum_aktualizace', models.DateTimeField(auto_now=True, verbose_name='Datum aktualizace')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena')),
                ('dodavatel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dodavatel')),
                ('servisni_cislo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Servisní číslo')),
                ('posledni_zmena_uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zmenene_objednavky', to='users.webuser', verbose_name='Poslední změna uživatel')),
                ('zalozil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalozene_objednavky', to='users.webuser', verbose_name='Založil')),
            ],
            options={
                'verbose_name': 'Objednávka',
                'verbose_name_plural': 'Objednávky',
                'db_table': 'WEB_OBJEDNAVKY',
                'ordering': ['-datum_vytvoreni'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puvodni_status', models.CharField(choices=[('nove', 'Nové'), ('objednano', 'Objednáno'), ('v_kosiku', 'V košíku'), ('predobjednano', 'Předobjednáno'), ('neni_skladem', 'Není skladem'), ('storno', 'Storno'), ('dorazilo_ceka', 'Dorazilo čeká na zákazníka'), ('hotovo', 'Hotovo')], max_length=20, verbose_name='Původní stav')),
                ('novy_status', models.CharField(choices=[('nove', 'Nové'), ('objednano', 'Objednáno'), ('v_kosiku', 'V košíku'), ('predobjednano', 'Předobjednáno'), ('neni_skladem', 'Není skladem'), ('storno', 'Storno'), ('dorazilo_ceka', 'Dorazilo čeká na zákazníka'), ('hotovo', 'Hotovo')], max_length=20, verbose_name='Nový stav')),
                ('datum_zmeny', models.DateTimeField(auto_now_add=True, verbose_name='Datum změny')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka ke změně')),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie_stavu', to='orders.order', verbose_name='Objednávka')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.webuser', verbose_name='Změnil uživatel')),
            ],
            options={
                'verbose_name': 'Historie stavů objednávky',
                'verbose_name_plural': 'Historie stavů objednávek',
                'db_table': 'WEB_OBJEDNAVKY_HISTORIE',
                'ordering': ['-datum_zmeny'],
            },
        ),
    ]
