# Generated by Django 5.x on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='symplio_objednavka_id',
            field=models.CharField(
                blank=True,
                help_text='ID v Symplio adminu (odkaz /admin/objednavky/objednavka-{id})',
                max_length=64,
                null=True,
                verbose_name='Symplio ID objednávky',
            ),
        ),
        migrations.AddField(
            model_name='order',
            name='sla_reminder_sent_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='SLA připomínka odeslána',
            ),
        ),
    ]
