# Generated by Django 4.2.23 on 2026-07-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_prodejna_vedouci_prodejny'),
        ('orders', '0002_order_symplio_sla'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prodejna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objednavky', to='stores.prodejna', verbose_name='Prodejna'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nove', 'Nové'), ('v_kosiku', 'v košíku'), ('objednano', 'objednáno'), ('predobjednano', 'Předobjednáno'), ('neni_skladem', 'Není skladem'), ('storno', 'Storno'), ('dorazilo_ceka', 'připraveno'), ('hotovo', 'vyřízeno')], default='nove', max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='novy_status',
            field=models.CharField(choices=[('nove', 'Nové'), ('v_kosiku', 'v košíku'), ('objednano', 'objednáno'), ('predobjednano', 'Předobjednáno'), ('neni_skladem', 'Není skladem'), ('storno', 'Storno'), ('dorazilo_ceka', 'připraveno'), ('hotovo', 'vyřízeno')], max_length=20, verbose_name='Nový stav'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='puvodni_status',
            field=models.CharField(choices=[('nove', 'Nové'), ('v_kosiku', 'v košíku'), ('objednano', 'objednáno'), ('predobjednano', 'Předobjednáno'), ('neni_skladem', 'Není skladem'), ('storno', 'Storno'), ('dorazilo_ceka', 'připraveno'), ('hotovo', 'vyřízeno')], max_length=20, verbose_name='Původní stav'),
        ),
    ]
