# Generated by Django 4.2.23 on 2026-10-01 09:14

from django.db import migrations, models
import django.db.models.deletion
import knowledge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0028_app_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255, verbose_name='Název')),
                ('popis', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('soubor', models.FileField(upload_to=knowledge.models.knowledge_upload_path, verbose_name='Soubor')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('velikost', models.PositiveIntegerField(default=0, verbose_name='Velikost v bytech')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Vytěžený text')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('nahral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to='users.webuser', verbose_name='Nahrál')),
            ],
            options={
                'verbose_name': 'Dokument znalostní báze',
                'verbose_name_plural': 'Dokumenty znalostní báze',
                'db_table': 'WEB_KNOWLEDGE',
                'ordering': ['-vytvoreno'],
            },
        ),
    ]
