# Generated by Django 4.2.23 on 2026-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WreckPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Model')),
                ('part_type', models.CharField(max_length=100, verbose_name='Typ dílu')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Počet')),
                ('store', models.CharField(max_length=100, verbose_name='Prodejna')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Poznámka')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Díl z vraku',
                'verbose_name_plural': 'Díly z vraků',
                'db_table': 'WEB_DILY_Z_VRAKU',
                'ordering': ['store', 'model_name', 'part_type'],
            },
        ),
    ]
