# Generated by Django 4.2.23 on 2025-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('spreadsheet_id', models.CharField(max_length=200)),
                ('daily_sheet_name', models.CharField(default='List 1', max_length=100)),
                ('monthly_sheet_name', models.CharField(default='od 1', max_length=100)),
                ('api_key', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheets konfigurace',
                'verbose_name_plural': 'Google Sheets konfigurace',
                'db_table': 'WEB_GOOGLE_SHEETS_CONFIG',
            },
        ),
        migrations.CreateModel(
            name='ProdejniData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('daily', 'Denní data'), ('monthly', 'Měsíční data')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prodejna', models.CharField(max_length=100)),
                ('prodejce', models.CharField(max_length=100)),
                ('id_prodejce', models.IntegerField(blank=True, null=True)),
                ('polozky_nad_100', models.IntegerField(default=0)),
                ('sluzby_celkem', models.IntegerField(default=0)),
                ('pol_dok', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ct300', models.IntegerField(default=0)),
                ('ct600', models.IntegerField(default=0)),
                ('ct1200', models.IntegerField(default=0)),
                ('akt', models.IntegerField(default=0)),
                ('zah250', models.IntegerField(default=0)),
                ('nap', models.IntegerField(default=0)),
                ('zah500', models.IntegerField(default=0)),
                ('kop250', models.IntegerField(default=0)),
                ('kop500', models.IntegerField(default=0)),
                ('pz1', models.IntegerField(default=0)),
                ('knz', models.IntegerField(default=0)),
                ('aligator', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Prodejní data',
                'verbose_name_plural': 'Prodejní data',
                'db_table': 'WEB_PRODEJNI_DATA',
                'ordering': ['-timestamp', 'prodejna', 'prodejce'],
                'indexes': [models.Index(fields=['data_type', 'timestamp'], name='WEB_PRODEJN_data_ty_d6ef9c_idx'), models.Index(fields=['prodejna'], name='WEB_PRODEJN_prodejn_8e1022_idx'), models.Index(fields=['prodejce'], name='WEB_PRODEJN_prodejc_f7a6c9_idx')],
            },
        ),
    ]
