# Generated by Django 4.2.23 on 2025-07-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdejniDataDenni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prodejna', models.CharField(max_length=100)),
                ('prodejce', models.CharField(max_length=100)),
                ('id_prodejce', models.IntegerField(blank=True, null=True)),
                ('polozky_nad_100', models.IntegerField(default=0)),
                ('sluzby_celkem', models.IntegerField(default=0)),
                ('pol_dok', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ct300', models.IntegerField(default=0)),
                ('ct600', models.IntegerField(default=0)),
                ('ct1200', models.IntegerField(default=0)),
                ('akt', models.IntegerField(default=0)),
                ('zah250', models.IntegerField(default=0)),
                ('nap', models.IntegerField(default=0)),
                ('zah500', models.IntegerField(default=0)),
                ('kop250', models.IntegerField(default=0)),
                ('kop500', models.IntegerField(default=0)),
                ('pz1', models.IntegerField(default=0)),
                ('knz', models.IntegerField(default=0)),
                ('aligator', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Denní prodejní data',
                'verbose_name_plural': 'Denní prodejní data',
                'db_table': 'WEB_PRODEJNI_DATA_DENNI',
                'ordering': ['-timestamp', 'prodejna', 'prodejce'],
            },
        ),
        migrations.CreateModel(
            name='ProdejniDataMesicni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prodejna', models.CharField(max_length=100)),
                ('prodejce', models.CharField(max_length=100)),
                ('id_prodejce', models.IntegerField(blank=True, null=True)),
                ('polozky_nad_100', models.IntegerField(default=0)),
                ('sluzby_celkem', models.IntegerField(default=0)),
                ('pol_dok', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ct300', models.IntegerField(default=0)),
                ('ct600', models.IntegerField(default=0)),
                ('ct1200', models.IntegerField(default=0)),
                ('akt', models.IntegerField(default=0)),
                ('zah250', models.IntegerField(default=0)),
                ('nap', models.IntegerField(default=0)),
                ('zah500', models.IntegerField(default=0)),
                ('kop250', models.IntegerField(default=0)),
                ('kop500', models.IntegerField(default=0)),
                ('pz1', models.IntegerField(default=0)),
                ('knz', models.IntegerField(default=0)),
                ('aligator', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Měsíční prodejní data',
                'verbose_name_plural': 'Měsíční prodejní data',
                'db_table': 'WEB_PRODEJNI_DATA_MESICNI',
                'ordering': ['-timestamp', 'prodejna', 'prodejce'],
            },
        ),
        migrations.AlterModelOptions(
            name='prodejnidata',
            options={'ordering': ['-timestamp', 'prodejna', 'prodejce'], 'verbose_name': 'Prodejní data (deprecated)', 'verbose_name_plural': 'Prodejní data (deprecated)'},
        ),
        migrations.RemoveIndex(
            model_name='prodejnidata',
            name='WEB_PRODEJN_data_ty_d6ef9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidata',
            name='WEB_PRODEJN_prodejn_8e1022_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidata',
            name='WEB_PRODEJN_prodejc_f7a6c9_idx',
        ),
        migrations.AlterField(
            model_name='prodejnidata',
            name='data_type',
            field=models.CharField(choices=[('daily', 'Denní data'), ('monthly', 'Měsíční data')], default='daily', max_length=10),
        ),
        migrations.AddIndex(
            model_name='prodejnidatamesicni',
            index=models.Index(fields=['timestamp'], name='WEB_PRODEJN_timesta_e1977e_idx'),
        ),
        migrations.AddIndex(
            model_name='prodejnidatamesicni',
            index=models.Index(fields=['prodejna'], name='WEB_PRODEJN_prodejn_e690e2_idx'),
        ),
        migrations.AddIndex(
            model_name='prodejnidatamesicni',
            index=models.Index(fields=['prodejce'], name='WEB_PRODEJN_prodejc_226930_idx'),
        ),
        migrations.AddIndex(
            model_name='prodejnidatamesicni',
            index=models.Index(fields=['timestamp', 'prodejna'], name='WEB_PRODEJN_timesta_35c846_idx'),
        ),
        migrations.AddIndex(
            model_name='prodejnidatadenni',
            index=models.Index(fields=['timestamp'], name='WEB_PRODEJN_timesta_3b95cc_idx'),
        ),
        migrations.AddIndex(
            model_name='prodejnidatadenni',
            index=models.Index(fields=['prodejna'], name='WEB_PRODEJN_prodejn_0a6358_idx'),
        ),
        migrations.AddIndex(
            model_name='prodejnidatadenni',
            index=models.Index(fields=['prodejce'], name='WEB_PRODEJN_prodejc_512d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='prodejnidatadenni',
            index=models.Index(fields=['timestamp', 'prodejna'], name='WEB_PRODEJN_timesta_e9df4e_idx'),
        ),
    ]
