# Generated by Django 4.2.23 on 2025-07-20 18:54

import analytics.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_webuser_adresa_webuser_email_webuser_poznamka_and_more'),
        ('analytics', '0002_prodejnidatadenni_prodejnidatamesicni_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodejnidatadenni',
            options={'verbose_name': 'Denní prodejní data', 'verbose_name_plural': 'Denní prodejní data'},
        ),
        migrations.AlterModelOptions(
            name='prodejnidatamesicni',
            options={'verbose_name': 'Měsíční prodejní data', 'verbose_name_plural': 'Měsíční prodejní data'},
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatadenni',
            name='WEB_PRODEJN_timesta_3b95cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatadenni',
            name='WEB_PRODEJN_prodejn_0a6358_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatadenni',
            name='WEB_PRODEJN_prodejc_512d7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatadenni',
            name='WEB_PRODEJN_timesta_e9df4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatamesicni',
            name='WEB_PRODEJN_timesta_e1977e_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatamesicni',
            name='WEB_PRODEJN_prodejn_e690e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatamesicni',
            name='WEB_PRODEJN_prodejc_226930_idx',
        ),
        migrations.RemoveIndex(
            model_name='prodejnidatamesicni',
            name='WEB_PRODEJN_timesta_35c846_idx',
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='body',
            field=models.IntegerField(default=0, verbose_name='Celkové body'),
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='datum',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='datum_upravy',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum úpravy'),
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='datum_vytvoreni',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Datum vytvoření'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='prumer_polozek_uctu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Průměr položek/účtu'),
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.webuser', verbose_name='Uživatel'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='body',
            field=models.IntegerField(default=0, verbose_name='Celkové body'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='datum_upravy',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum úpravy'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='datum_vytvoreni',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Datum vytvoření'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='mesic',
            field=models.IntegerField(default=analytics.models.get_current_month, verbose_name='Měsíc'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='prumer_polozek_uctu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Průměr položek/účtu'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='rok',
            field=models.IntegerField(default=analytics.models.get_current_year, verbose_name='Rok'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.webuser', verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='akt',
            field=models.IntegerField(default=0, verbose_name='AKT'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='aligator',
            field=models.IntegerField(default=0, verbose_name='ALIGATOR'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='ct1200',
            field=models.IntegerField(default=0, verbose_name='CT1200'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='ct300',
            field=models.IntegerField(default=0, verbose_name='CT300'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='ct600',
            field=models.IntegerField(default=0, verbose_name='CT600'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='knz',
            field=models.IntegerField(default=0, verbose_name='KNZ'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='kop250',
            field=models.IntegerField(default=0, verbose_name='KOP250'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='kop500',
            field=models.IntegerField(default=0, verbose_name='KOP500'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='nap',
            field=models.IntegerField(default=0, verbose_name='NAP'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='polozky_nad_100',
            field=models.IntegerField(default=0, verbose_name='Položky nad 100 Kč'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='pz1',
            field=models.IntegerField(default=0, verbose_name='PZ1'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='sluzby_celkem',
            field=models.IntegerField(default=0, verbose_name='Služby celkem'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='zah250',
            field=models.IntegerField(default=0, verbose_name='ZAH250'),
        ),
        migrations.AlterField(
            model_name='prodejnidatadenni',
            name='zah500',
            field=models.IntegerField(default=0, verbose_name='ZAH500'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='akt',
            field=models.IntegerField(default=0, verbose_name='AKT'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='aligator',
            field=models.IntegerField(default=0, verbose_name='ALIGATOR'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='ct1200',
            field=models.IntegerField(default=0, verbose_name='CT1200'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='ct300',
            field=models.IntegerField(default=0, verbose_name='CT300'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='ct600',
            field=models.IntegerField(default=0, verbose_name='CT600'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='knz',
            field=models.IntegerField(default=0, verbose_name='KNZ'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='kop250',
            field=models.IntegerField(default=0, verbose_name='KOP250'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='kop500',
            field=models.IntegerField(default=0, verbose_name='KOP500'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='nap',
            field=models.IntegerField(default=0, verbose_name='NAP'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='polozky_nad_100',
            field=models.IntegerField(default=0, verbose_name='Položky nad 100 Kč'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='pz1',
            field=models.IntegerField(default=0, verbose_name='PZ1'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='sluzby_celkem',
            field=models.IntegerField(default=0, verbose_name='Služby celkem'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='zah250',
            field=models.IntegerField(default=0, verbose_name='ZAH250'),
        ),
        migrations.AlterField(
            model_name='prodejnidatamesicni',
            name='zah500',
            field=models.IntegerField(default=0, verbose_name='ZAH500'),
        ),
        migrations.AlterUniqueTogether(
            name='prodejnidatadenni',
            unique_together={('uzivatel', 'datum')},
        ),
        migrations.AlterUniqueTogether(
            name='prodejnidatamesicni',
            unique_together={('uzivatel', 'rok', 'mesic')},
        ),
        migrations.AlterModelTable(
            name='prodejnidatadenni',
            table='WEB_ANALYTICS_PRODEJNIDATADENNI',
        ),
        migrations.AlterModelTable(
            name='prodejnidatamesicni',
            table='WEB_ANALYTICS_PRODEJNIDATAMESICNI',
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='id_prodejce',
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='pol_dok',
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='prodejce',
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='prodejna',
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='id_prodejce',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='pol_dok',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='prodejce',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='prodejna',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='timestamp',
        ),
    ]
