# Generated by Django 4.2.23 on 2025-07-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_prodejnidatadenni_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='body',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='body',
        ),
    ]
