# Generated by Django 4.2.23 on 2025-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_prodejnidatadenni_body_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prodejnidatadenni',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prodejnidatamesicni',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='jmeno_prodejce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jméno prodejce'),
        ),
        migrations.AddField(
            model_name='prodejnidatadenni',
            name='nazev_prodejny',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Název prodejny'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='jmeno_prodejce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jméno prodejce'),
        ),
        migrations.AddField(
            model_name='prodejnidatamesicni',
            name='nazev_prodejny',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Název prodejny'),
        ),
        migrations.AlterUniqueTogether(
            name='prodejnidatadenni',
            unique_together={('datum', 'jmeno_prodejce', 'nazev_prodejny')},
        ),
        migrations.AlterUniqueTogether(
            name='prodejnidatamesicni',
            unique_together={('rok', 'mesic', 'jmeno_prodejce', 'nazev_prodejny')},
        ),
    ]
