# Generated by Django 4.2.23 on 2025-07-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_webuser_prodejna'),
        ('analytics', '0006_alter_prodejnidatadenni_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesheetsconfig',
            options={'verbose_name': 'Google Sheets konfigurace (deprecated)', 'verbose_name_plural': 'Google Sheets konfigurace (deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='prodejnidatadenni',
            options={'verbose_name': 'Denní prodejní data (deprecated)', 'verbose_name_plural': 'Denní prodejní data (deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='prodejnidatamesicni',
            options={'verbose_name': 'Měsíční prodejní data (deprecated)', 'verbose_name_plural': 'Měsíční prodejní data (deprecated)'},
        ),
        migrations.AlterField(
            model_name='googlesheetsconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='prodejnidatadenni',
            unique_together={('uzivatel', 'datum')},
        ),
        migrations.AlterUniqueTogether(
            name='prodejnidatamesicni',
            unique_together={('uzivatel', 'rok', 'mesic')},
        ),
        migrations.CreateModel(
            name='WebProdeje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(blank=True, max_length=100, null=True, verbose_name='Datum prodeje')),
                ('kod', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kód položky')),
                ('nazev', models.TextField(blank=True, null=True, verbose_name='Název položky')),
                ('doklad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Číslo účtenky/faktury')),
                ('nazev_dokladu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Název dokladu')),
                ('objednavka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Číslo objednávky')),
                ('polozka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Položka dokladu')),
                ('stredisko', models.CharField(blank=True, max_length=100, null=True, verbose_name='Název prodejny')),
                ('spravce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Správce')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka k položce')),
                ('poznamka_dokladu', models.TextField(blank=True, null=True, verbose_name='Poznámka k dokladu')),
                ('pocet_kusu', models.IntegerField(blank=True, null=True, verbose_name='Počet kusů')),
                ('cena_ks_vcl_dph', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prodejní cena s DPH')),
                ('skladova_cena_bez_dph', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nákupní cena bez DPH')),
                ('skladova_cena_bez_dph_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Celková nákupní cena')),
                ('marketingovy_kanal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marketing kanál')),
                ('dropshipping', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dropshipping')),
                ('id_prodejce', models.IntegerField(blank=True, null=True, verbose_name='ID prodejce')),
                ('id_prodejny', models.IntegerField(blank=True, null=True, verbose_name='ID prodejny')),
                ('zisk', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Zisk')),
                ('kategorie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hlavní kategorie')),
                ('kategorie_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Podkategorie 1')),
                ('kategorie_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Podkategorie 2')),
                ('datum_vlozeni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vložení do DB')),
            ],
            options={
                'verbose_name': 'Prodejní položka',
                'verbose_name_plural': 'Prodejní položky',
                'db_table': 'WEB_PRODEJE',
                'ordering': ['-datum_vlozeni', '-id'],
                'indexes': [models.Index(fields=['typ'], name='idx_prodeje_typ'), models.Index(fields=['id_prodejce'], name='idx_prodeje_prodejce'), models.Index(fields=['id_prodejny'], name='idx_prodeje_prodejny'), models.Index(fields=['marketingovy_kanal'], name='idx_prodeje_kanal'), models.Index(fields=['kategorie'], name='idx_prodeje_kategorie'), models.Index(fields=['stredisko'], name='idx_prodeje_stredisko')],
            },
        ),
        migrations.CreateModel(
            name='PolozkyMesicni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodejce', models.CharField(max_length=100, verbose_name='Prodejce')),
                ('id_prodejce', models.IntegerField(verbose_name='ID Prodejce')),
                ('prodejna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prodejna')),
                ('id_prodejna', models.IntegerField(blank=True, null=True, verbose_name='ID Prodejny')),
                ('nad_100', models.IntegerField(default=0, verbose_name='Položky nad 100 Kč')),
                ('sluzby', models.IntegerField(default=0, verbose_name='Služby celkem')),
                ('pol_dok', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Průměr položek/účtu')),
                ('ct300', models.IntegerField(default=0, verbose_name='CT300')),
                ('ct600', models.IntegerField(default=0, verbose_name='CT600')),
                ('ct1200', models.IntegerField(default=0, verbose_name='CT1200')),
                ('akt', models.IntegerField(default=0, verbose_name='AKT')),
                ('zah250', models.IntegerField(default=0, verbose_name='ZAH250')),
                ('nap', models.IntegerField(default=0, verbose_name='NAP')),
                ('zah500', models.IntegerField(default=0, verbose_name='ZAH500')),
                ('kop250', models.IntegerField(default=0, verbose_name='KOP250')),
                ('kop500', models.IntegerField(default=0, verbose_name='KOP500')),
                ('pz1', models.IntegerField(default=0, verbose_name='PZ1')),
                ('knz', models.IntegerField(default=0, verbose_name='KNZ')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('mesic_rok', models.CharField(max_length=7, verbose_name='Měsíc-Rok')),
            ],
            options={
                'verbose_name': 'Měsíční položky (Apify)',
                'verbose_name_plural': 'Měsíční položky (Apify)',
                'db_table': 'WEB_POLOZKY_MESICNI',
                'ordering': ['-mesic_rok', '-timestamp'],
                'indexes': [models.Index(fields=['id_prodejce', 'mesic_rok'], name='WEB_POLOZKY_id_prod_2a7779_idx'), models.Index(fields=['mesic_rok'], name='WEB_POLOZKY_mesic_r_83be40_idx'), models.Index(fields=['timestamp'], name='WEB_POLOZKY_timesta_002548_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolozkyDenni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodejce', models.CharField(max_length=100, verbose_name='Prodejce')),
                ('id_prodejce', models.IntegerField(verbose_name='ID Prodejce')),
                ('prodejna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prodejna')),
                ('id_prodejna', models.IntegerField(blank=True, null=True, verbose_name='ID Prodejny')),
                ('nad_100', models.IntegerField(default=0, verbose_name='Položky nad 100 Kč')),
                ('sluzby', models.IntegerField(default=0, verbose_name='Služby celkem')),
                ('pol_dok', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Průměr položek/účtu')),
                ('ct300', models.IntegerField(default=0, verbose_name='CT300')),
                ('ct600', models.IntegerField(default=0, verbose_name='CT600')),
                ('ct1200', models.IntegerField(default=0, verbose_name='CT1200')),
                ('akt', models.IntegerField(default=0, verbose_name='AKT')),
                ('zah250', models.IntegerField(default=0, verbose_name='ZAH250')),
                ('nap', models.IntegerField(default=0, verbose_name='NAP')),
                ('zah500', models.IntegerField(default=0, verbose_name='ZAH500')),
                ('kop250', models.IntegerField(default=0, verbose_name='KOP250')),
                ('kop500', models.IntegerField(default=0, verbose_name='KOP500')),
                ('pz1', models.IntegerField(default=0, verbose_name='PZ1')),
                ('knz', models.IntegerField(default=0, verbose_name='KNZ')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('datum', models.DateField(verbose_name='Datum')),
            ],
            options={
                'verbose_name': 'Denní položky (Apify)',
                'verbose_name_plural': 'Denní položky (Apify)',
                'db_table': 'WEB_POLOZKY_DENNI',
                'ordering': ['-datum', '-timestamp'],
                'indexes': [models.Index(fields=['id_prodejce', 'datum'], name='WEB_POLOZKY_id_prod_bb183d_idx'), models.Index(fields=['datum'], name='WEB_POLOZKY_datum_fe1186_idx'), models.Index(fields=['timestamp'], name='WEB_POLOZKY_timesta_a4e7ac_idx')],
            },
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='jmeno_prodejce',
        ),
        migrations.RemoveField(
            model_name='prodejnidatadenni',
            name='nazev_prodejny',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='jmeno_prodejce',
        ),
        migrations.RemoveField(
            model_name='prodejnidatamesicni',
            name='nazev_prodejny',
        ),
    ]
