# Generated by Django 4.2.23 on 2025-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_create_web_prodeje_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webprodeje',
            name='cena_ks_vcl_dph',
            field=models.DecimalField(blank=True, db_column='Cena_ks_vcl_DPH', decimal_places=2, max_digits=10, null=True, verbose_name='Prodejní cena s DPH'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='datum_vlozeni',
            field=models.DateTimeField(auto_now_add=True, db_column='datum_vlozeni', verbose_name='Datum vložení do DB'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='doklad',
            field=models.CharField(blank=True, db_column='Doklad', max_length=100, null=True, verbose_name='Číslo účtenky/faktury'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='dropshipping',
            field=models.CharField(blank=True, db_column='Dropshipping', max_length=10, null=True, verbose_name='Dropshipping'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='id_prodejce',
            field=models.IntegerField(blank=True, db_column='ID_PRODEJCE', null=True, verbose_name='ID prodejce'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='id_prodejny',
            field=models.IntegerField(blank=True, db_column='ID_PRODEJNY', null=True, verbose_name='ID prodejny'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='kategorie',
            field=models.CharField(blank=True, db_column='KATEGORIE', max_length=255, null=True, verbose_name='Hlavní kategorie'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='kategorie_1',
            field=models.CharField(blank=True, db_column='KATEGORIE_1', max_length=255, null=True, verbose_name='Podkategorie 1'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='kategorie_2',
            field=models.CharField(blank=True, db_column='KATEGORIE_2', max_length=255, null=True, verbose_name='Podkategorie 2'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='kod',
            field=models.CharField(blank=True, db_column='Kod', max_length=100, null=True, verbose_name='Kód položky'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='marketingovy_kanal',
            field=models.CharField(blank=True, db_column='Marketingovy_kanal', max_length=100, null=True, verbose_name='Marketing kanál'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='nazev',
            field=models.TextField(blank=True, db_column='Nazev', null=True, verbose_name='Název položky'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='nazev_dokladu',
            field=models.CharField(blank=True, db_column='Nazev_dokladu', max_length=255, null=True, verbose_name='Název dokladu'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='objednavka',
            field=models.CharField(blank=True, db_column='Objednavka', max_length=100, null=True, verbose_name='Číslo objednávky'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='pocet_kusu',
            field=models.IntegerField(blank=True, db_column='Pocet_kusu', null=True, verbose_name='Počet kusů'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='polozka',
            field=models.CharField(blank=True, db_column='Polozka', max_length=100, null=True, verbose_name='Položka dokladu'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='poznamka',
            field=models.TextField(blank=True, db_column='Poznamka', null=True, verbose_name='Poznámka k položce'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='poznamka_dokladu',
            field=models.TextField(blank=True, db_column='Poznamka_dokladu', null=True, verbose_name='Poznámka k dokladu'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='skladova_cena_bez_dph',
            field=models.DecimalField(blank=True, db_column='Skladova_cena_bez_DPH', decimal_places=2, max_digits=10, null=True, verbose_name='Nákupní cena bez DPH'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='skladova_cena_bez_dph_total',
            field=models.DecimalField(blank=True, db_column='Skladova_cena_bez_DPH_total', decimal_places=2, max_digits=10, null=True, verbose_name='Celková nákupní cena'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='spravce',
            field=models.CharField(blank=True, db_column='Spravce', max_length=100, null=True, verbose_name='Správce'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='stredisko',
            field=models.CharField(blank=True, db_column='Stredisko', max_length=100, null=True, verbose_name='Název prodejny'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='typ',
            field=models.CharField(blank=True, db_column='Vystaveno', max_length=100, null=True, verbose_name='Datum prodeje'),
        ),
        migrations.AlterField(
            model_name='webprodeje',
            name='zisk',
            field=models.DecimalField(blank=True, db_column='ZISK', decimal_places=2, max_digits=10, null=True, verbose_name='Zisk'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['typ'], name='idx_prodeje_all_typ'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['id_prodejce'], name='idx_prodeje_all_prodejce'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['id_prodejny'], name='idx_prodeje_all_prodejny'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['marketingovy_kanal'], name='idx_prodeje_all_kanal'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['kategorie'], name='idx_prodeje_all_kategorie'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['stredisko'], name='idx_prodeje_all_stredisko'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['je_nad_100_kc'], name='idx_prodeje_all_nad_100'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['je_servisni_sluzba'], name='idx_prodeje_all_servis'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['je_eshop_prodej'], name='idx_prodeje_all_eshop'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['rok', 'mesic'], name='idx_prodeje_all_mesic_rok'),
        ),
        migrations.AddIndex(
            model_name='webprodejeall',
            index=models.Index(fields=['importovano_z_web_prodeje'], name='idx_prodeje_all_import'),
        ),
    ]
