# Generated by Django 4.2.23 on 2025-08-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_webprodeje_cena_ks_vcl_dph_and_more'),
        ('analytics', '0010_create_web_prodeje_all'),
    ]

    operations = [
    ]
