# Generated by Django 4.2.23 on 2025-10-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_merge_20250812_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebZasilkovna',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('prodejna', models.CharField(db_column='PRODEJNA', max_length=100, verbose_name='Název prodejny')),
                ('id_prodejna', models.IntegerField(db_column='ID_PRODEJNA', verbose_name='ID prodejny')),
                ('rok', models.IntegerField(db_column='ROK', verbose_name='Rok')),
                ('mesic', models.IntegerField(db_column='MESIC', verbose_name='Měsíc')),
                ('za_zpracovani', models.DecimalField(blank=True, db_column='ZA_ZPRACOVANI', decimal_places=2, max_digits=10, null=True, verbose_name='Za zpracování')),
                ('za_vyber_dobirky', models.DecimalField(blank=True, db_column='ZA_VYBER_DOBIRKY', decimal_places=2, max_digits=10, null=True, verbose_name='Za výběr dobírky')),
                ('ostatni_provize', models.DecimalField(blank=True, db_column='OSTATNI_PROVIZE', decimal_places=2, max_digits=10, null=True, verbose_name='Ostatní provize')),
                ('celkove_provize_mesic', models.DecimalField(blank=True, db_column='CELKOVE_PROVIZE_MESIC', decimal_places=2, max_digits=10, null=True, verbose_name='Celkové provize za měsíc')),
                ('k_vyplate_mesic', models.DecimalField(blank=True, db_column='K_VYPLATE_MESIC', decimal_places=2, max_digits=10, null=True, verbose_name='K výplatě za měsíc')),
                ('fakturovano', models.CharField(db_column='FAKTUROVANO', default='NE', max_length=10, verbose_name='Fakturováno')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='Datum vytvoření')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', verbose_name='Datum aktualizace')),
            ],
            options={
                'verbose_name': 'Zásilkovna provize',
                'verbose_name_plural': 'Zásilkovna provize',
                'db_table': 'WEB_ZASILKOVNA',
                'ordering': ['-rok', '-mesic', 'prodejna'],
            },
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_typ',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_prodejce',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_prodejny',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_kanal',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_kategorie',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_stredisko',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_nad_100',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_servis',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_eshop',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_mesic_rok',
        ),
        migrations.RemoveIndex(
            model_name='webprodejeall',
            name='idx_prodeje_all_import',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='celkova_hodnota_dokladu',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='datum_posledni_aktualizace',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='datum_upravy',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='den_v_tydnu',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='importovano_z_web_prodeje',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_accessory',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_allegro_prodej',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_eshop_prodej',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_hlavni_prodejce',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_nad_100_kc',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_servisni_sluzba',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_smart_watch',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_tablet',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='je_telefon',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='kvartal',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='marze_procenta',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='mesic',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='nazev_dokladu',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='nazev_prodejce',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='pocet_polozek_v_dokladu',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='polozka',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='pozice_v_dokladu',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='poznamka_dokladu',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='rok',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='skladova_cena_bez_dph_total',
        ),
        migrations.RemoveField(
            model_name='webprodejeall',
            name='tyden_v_roce',
        ),
        migrations.AddField(
            model_name='webprodejeall',
            name='cena_ks_bez_dph',
            field=models.DecimalField(blank=True, db_column='Cena_ks_bez_DPH', decimal_places=2, max_digits=10, null=True, verbose_name='Prodejní cena bez DPH'),
        ),
        migrations.AddField(
            model_name='webprodejeall',
            name='k_servisu',
            field=models.CharField(blank=True, db_column='k_servisu', max_length=10, null=True, verbose_name='K servisu'),
        ),
        migrations.AddField(
            model_name='webprodejeall',
            name='kategorie_puvodni',
            field=models.TextField(blank=True, db_column='Kategorie_puvodni', null=True, verbose_name='Původní kategorie'),
        ),
        migrations.AddField(
            model_name='webprodejeall',
            name='objednavku_zalozil',
            field=models.CharField(blank=True, db_column='Objednavku_zalozil', max_length=100, null=True, verbose_name='Objednávku založil'),
        ),
        migrations.AddField(
            model_name='webprodejeall',
            name='pokladna',
            field=models.CharField(blank=True, db_column='Pokladna', max_length=100, null=True, verbose_name='Pokladna'),
        ),
        migrations.AddField(
            model_name='webprodejeall',
            name='poznamka_zakaznika',
            field=models.TextField(blank=True, db_column='Poznamka_zakaznika', null=True, verbose_name='Poznámka zákazníka'),
        ),
        migrations.AddField(
            model_name='webprodejeall',
            name='technik',
            field=models.CharField(blank=True, db_column='Technik', max_length=100, null=True, verbose_name='Technik'),
        ),
        migrations.AddIndex(
            model_name='webzasilkovna',
            index=models.Index(fields=['rok', 'mesic'], name='idx_zasilkovna_rok_mesic'),
        ),
        migrations.AddIndex(
            model_name='webzasilkovna',
            index=models.Index(fields=['id_prodejna'], name='idx_zasilkovna_prodejna'),
        ),
        migrations.AlterUniqueTogether(
            name='webzasilkovna',
            unique_together={('prodejna', 'rok', 'mesic')},
        ),
    ]
