# Generated by Django 4.2.23 on 2026-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_leaderboard_cache_points_by_prodejna'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebVykupy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vystaveno', models.DateField(db_column='Vystaveno')),
                ('vystaveno_cas', models.TimeField(blank=True, db_column='Vystaveno_cas', null=True)),
                ('kod', models.CharField(blank=True, db_column='Kod', max_length=50, null=True)),
                ('nazev', models.TextField(blank=True, db_column='Nazev', null=True)),
                ('stredisko', models.CharField(blank=True, db_column='Stredisko', max_length=100, null=True)),
                ('pocet_kusů', models.IntegerField(db_column='Pocet_kusu', default=0)),
                ('cena_ks_bez_dph', models.DecimalField(blank=True, db_column='Cena_ks_bez_DPH', decimal_places=2, max_digits=12, null=True)),
                ('spravce', models.CharField(blank=True, db_column='Spravce', max_length=100, null=True)),
                ('kategorie', models.CharField(blank=True, db_column='Kategorie', max_length=100, null=True)),
                ('id_prodejny', models.IntegerField(blank=True, db_column='ID_PRODEJNY', null=True)),
                ('id_prodejce', models.IntegerField(blank=True, db_column='ID_PRODEJCE', null=True)),
            ],
            options={
                'verbose_name': 'Výkup',
                'verbose_name_plural': 'Výkupy',
                'db_table': 'WEB_VYKUPY',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='leaderboardmonthpointscache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # Sloupec Vystaveno spravuje externí actor – jen sjednotit stav modelu v Django.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='webprodejeall',
                    name='typ',
                    field=models.DateField(
                        blank=True, db_column='Vystaveno', null=True, verbose_name='Datum prodeje',
                    ),
                ),
            ],
        ),
    ]
