# Generated by Django 4.2.23 on 2026-06-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_ukol_dokonceno_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='ukol',
            name='blokovano_duvod',
            field=models.TextField(blank=True, db_column='BLOKOVANO_DUVOD', default=''),
        ),
        migrations.AddField(
            model_name='ukol',
            name='dod_polozky',
            field=models.JSONField(blank=True, db_column='DOD_POLOZKY', default=list),
        ),
        migrations.AddField(
            model_name='ukol',
            name='mid_kontrola_v',
            field=models.DateTimeField(blank=True, db_column='MID_KONTROLA_V', null=True),
        ),
        migrations.AddField(
            model_name='ukol',
            name='popis',
            field=models.TextField(blank=True, db_column='POPIS', default=''),
        ),
        migrations.AddField(
            model_name='ukol',
            name='posledni_aktivita_v',
            field=models.DateTimeField(blank=True, db_column='POSLEDNI_AKTIVITA_V', null=True),
        ),
        migrations.AddField(
            model_name='ukol',
            name='prvni_krok',
            field=models.CharField(blank=True, db_column='PRVNI_KROK', default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ukol',
            name='schvaleno_v',
            field=models.DateTimeField(blank=True, db_column='SCHVALENO_V', null=True),
        ),
        migrations.AddField(
            model_name='ukol',
            name='schvalil_id',
            field=models.IntegerField(blank=True, db_column='SCHVALIL_ID', null=True),
        ),
        migrations.AddField(
            model_name='ukol',
            name='start_potvrzeno_v',
            field=models.DateTimeField(blank=True, db_column='START_POTVRZENO_V', null=True),
        ),
        migrations.AddField(
            model_name='ukol',
            name='vysledek',
            field=models.TextField(blank=True, db_column='VYSLEDEK', default=''),
        ),
        migrations.AddField(
            model_name='ukol',
            name='vyzaduje_schvaleni',
            field=models.BooleanField(db_column='VYZADUJE_SCHVALENI', default=False),
        ),
        migrations.AlterField(
            model_name='ukol',
            name='stav',
            field=models.CharField(choices=[('novy', 'Nový'), ('v_procesu', 'V procesu'), ('blokovany', 'Blokovaný'), ('ceka_schvaleni', 'Čeká schválení'), ('hotovo', 'Hotovo')], db_column='STAV', default='novy', max_length=20),
        ),
    ]
