# Generated by Django 4.2.23 on 2026-06-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_ukol_sop'),
    ]

    operations = [
        migrations.CreateModel(
            name='UkolSlackNotifikace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('due_soon', 'Blíží se termín'), ('overdue', 'Po termínu')], db_column='TYP', max_length=20)),
                ('odeslano_v', models.DateTimeField(auto_now_add=True, db_column='ODESLANO_V')),
                ('ukol', models.ForeignKey(db_column='UKOL_ID', on_delete=django.db.models.deletion.CASCADE, related_name='slack_notifikace', to='tasks.ukol')),
            ],
            options={
                'db_table': 'WEB_UKOLY_SLACK_NOTIF',
            },
        ),
        migrations.AddConstraint(
            model_name='ukolslacknotifikace',
            constraint=models.UniqueConstraint(fields=('ukol', 'typ'), name='uniq_ukol_slack_typ'),
        ),
    ]
