# Generated by Django 4.2.23 on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_ukol_slack_notifikace'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ukolslacknotifikace',
            name='uniq_ukol_slack_typ',
        ),
        migrations.AddField(
            model_name='ukolslacknotifikace',
            name='recipient_user_id',
            field=models.IntegerField(
                blank=True,
                db_column='RECIPIENT_USER_ID',
                help_text='WebUser ID příjemce DM; null u webhook notifikací.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='ukolslacknotifikace',
            name='typ',
            field=models.CharField(
                choices=[
                    ('due_soon', 'Blíží se termín (webhook)'),
                    ('overdue', 'Po termínu (webhook)'),
                    ('dm_assigned', 'DM – přiřazení'),
                    ('dm_due_soon', 'DM – blíží se termín'),
                    ('dm_overdue', 'DM – po termínu'),
                    ('dm_completed', 'DM – hotovo'),
                    ('dm_awaiting_approval', 'DM – čeká schválení'),
                    ('dm_created', 'DM – potvrzení zadavateli'),
                ],
                db_column='TYP',
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name='ukolslacknotifikace',
            constraint=models.UniqueConstraint(
                fields=('ukol', 'typ', 'recipient_user_id'),
                name='uniq_ukol_slack_typ_recipient',
            ),
        ),
    ]
