# Generated by Django 4.2.23 on 2026-06-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_ukol_shift_recap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackTaskDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(db_column='SLACK_USER_ID', max_length=32, unique=True)),
                ('channel_id', models.CharField(blank=True, db_column='CHANNEL_ID', default='', max_length=32)),
                ('web_user_id', models.IntegerField(db_column='WEB_USER_ID')),
                ('step', models.CharField(db_column='STEP', max_length=40)),
                ('data', models.JSONField(blank=True, db_column='DATA', default=dict)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, db_column='VYTVORENO')),
                ('upraveno', models.DateTimeField(auto_now=True, db_column='UPRAVENO')),
            ],
            options={
                'verbose_name': 'Slack draft úkolu',
                'verbose_name_plural': 'Slack drafty úkolů',
                'db_table': 'WEB_UKOLY_SLACK_DRAFT',
            },
        ),
        migrations.AlterField(
            model_name='ukolslacknotifikace',
            name='typ',
            field=models.CharField(choices=[('due_soon', 'Blíží se termín (webhook)'), ('overdue', 'Po termínu (webhook)'), ('dm_assigned', 'DM – přiřazení'), ('dm_due_soon', 'DM – blíží se termín'), ('dm_overdue', 'DM – po termínu'), ('dm_completed', 'DM – hotovo'), ('dm_awaiting_approval', 'DM – čeká schválení'), ('dm_created', 'DM – potvrzení zadavateli'), ('dm_comment', 'DM – nový komentář')], db_column='TYP', max_length=30),
        ),
    ]
