# Generated by Django 4.2.26 on 2026-03-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0011_remove_webuser_datum_upravy_alter_webuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok', models.IntegerField(verbose_name='Rok')),
                ('mesic', models.IntegerField(verbose_name='Měsíc (1–12)')),
                ('cislo_verze', models.IntegerField(default=1, verbose_name='Číslo verze')),
                ('je_aktualni', models.BooleanField(default=True, verbose_name='Je aktuální verze')),
                ('castka_celkem', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Celková částka firmy (Kč)')),
                ('vytvoreno_kdy', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno kdy')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plany_vytvorene', to='users.webuser', verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Měsíční plán',
                'verbose_name_plural': 'Měsíční plány',
                'db_table': 'WEB_PLANS_MONTH',
                'ordering': ['-rok', '-mesic', '-cislo_verze'],
                'unique_together': {('rok', 'mesic', 'cislo_verze')},
            },
        ),
        migrations.CreateModel(
            name='PlanStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podil_procenta', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Podíl (%)')),
                ('castka_prodejna', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Částka prodejny (Kč)')),
                ('zamknuto', models.BooleanField(default=False, verbose_name='Zamknuto')),
                ('castka_prodej', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Částka prodej (Kč)')),
                ('castka_servis', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Částka servis (Kč)')),
                ('plan_mesic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodejny', to='plans.planmonth', verbose_name='Měsíční plán')),
                ('prodejna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plany', to='stores.prodejna', verbose_name='Prodejna')),
            ],
            options={
                'verbose_name': 'Plán prodejny',
                'verbose_name_plural': 'Plány prodejen',
                'db_table': 'WEB_PLANS_STORE',
                'ordering': ['prodejna__poradi', 'prodejna__nazev'],
                'unique_together': {('plan_mesic', 'prodejna')},
            },
        ),
        migrations.CreateModel(
            name='PlanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie_kod', models.CharField(choices=[('NOVE_TELEFONY', 'Telefony nové'), ('BAZAROVE_TELEFONY', 'Telefony bazarové'), ('PRISLUSENSTVI', 'Příslušenství'), ('PRISLUSENSTVI_SKLA', 'Příslušenství – Skla'), ('PRISLUSENSTVI_OBALY', 'Příslušenství – Obaly'), ('PRISLUSENSTVI_OSTATNI', 'Příslušenství – Ostatní'), ('SLUZBY', 'Služby'), ('SERVIS', 'Servis'), ('OSTATNI', 'Ostatní')], max_length=30, verbose_name='Kategorie')),
                ('podil_procenta', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Podíl v rámci prodejny (%)')),
                ('castka_kategorie', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Částka kategorie (Kč)')),
                ('plan_prodejna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategorie', to='plans.planstore', verbose_name='Plán prodejny')),
            ],
            options={
                'verbose_name': 'Plán kategorie',
                'verbose_name_plural': 'Plány kategorií',
                'db_table': 'WEB_PLANS_CATEGORY',
                'ordering': ['kategorie_kod'],
                'unique_together': {('plan_prodejna', 'kategorie_kod')},
            },
        ),
    ]
