# Generated by Django 4.2.23 on 2026-09-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0024_smena_pozice_vypomoc'),
        ('users', '0028_app_activity_log'),
        ('plans', '0005_alter_planprodejce_id_alter_planprodejcekategorie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategorieZboziClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(db_index=True, max_length=100, verbose_name='P kód')),
                ('nazev', models.CharField(blank=True, default='', max_length=255, verbose_name='Název')),
                ('rok', models.IntegerField(verbose_name='Rok prodeje')),
                ('mesic', models.IntegerField(verbose_name='Měsíc prodeje')),
                ('stav', models.CharField(choices=[('ceka', 'Čeká na ověření'), ('potvrzeno', 'Potvrzeno'), ('nepotvrzeno', 'Nepotvrzeno')], default='ceka', max_length=16)),
                ('kategorie_pred', models.CharField(blank=True, default='', max_length=255)),
                ('kategorie_1_pred', models.CharField(blank=True, default='', max_length=255)),
                ('kategorie_po', models.CharField(blank=True, default='', max_length=255)),
                ('kategorie_1_po', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('poznamka', models.TextField(blank=True, default='')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('overeno', models.DateTimeField(blank=True, null=True)),
                ('odmena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategorie_zbozi_claimy', to='shifts.mzdovaodmenamesic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategorie_zbozi_claimy', to='users.webuser')),
            ],
            options={
                'verbose_name': 'Zařazení kategorie zboží',
                'verbose_name_plural': 'Zařazení kategorií zboží',
                'db_table': 'WEB_KATEGORIE_ZBOZI_CLAIM',
                'ordering': ['-vytvoreno'],
            },
        ),
    ]
