# Generated by Django 4.2.23 on 2026-06-24 09:05

from django.db import migrations, models
import django.db.models.deletion
import users.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('akce', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, default='')),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('vytvoreno', users.fields.SafeDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Finance audit log',
                'verbose_name_plural': 'Finance audit logy',
                'db_table': 'finance_audit_log',
                'ordering': ['-vytvoreno'],
            },
        ),
        migrations.CreateModel(
            name='FioKategorizacniPravidlo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protiucet', models.CharField(blank=True, default='', max_length=64)),
                ('zprava_obsahuje', models.CharField(blank=True, default='', max_length=200)),
                ('vs', models.CharField(blank=True, default='', max_length=32)),
                ('castka_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('castka_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prodejna_id', models.IntegerField(blank=True, null=True)),
                ('ignorovat', models.BooleanField(default=False)),
                ('aktivni', models.BooleanField(default=True)),
                ('vytvoril_user_id', models.IntegerField(blank=True, null=True)),
                ('vytvoreno', users.fields.SafeDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fio kategorizační pravidlo',
                'verbose_name_plural': 'Fio kategorizační pravidla',
                'db_table': 'finance_fio_pravidlo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NakladKategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=120, unique=True)),
                ('poradi', models.IntegerField(default=0)),
                ('aktivni', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategorie nákladu',
                'verbose_name_plural': 'Kategorie nákladů',
                'db_table': 'finance_naklad_kategorie',
                'ordering': ['poradi', 'nazev'],
            },
        ),
        migrations.CreateModel(
            name='NakladPolozka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('rok', models.IntegerField()),
                ('mesic', models.IntegerField()),
                ('castka', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prodejna_id', models.IntegerField(blank=True, null=True)),
                ('stav', models.CharField(choices=[('zarazeno', 'Zařazeno'), ('nezarazeno', 'Nezařazeno'), ('ignorovat', 'Ignorovat'), ('rucne_upraveno', 'Ručně upraveno')], default='nezarazeno', max_length=20)),
                ('zdroj', models.CharField(choices=[('fio', 'Fio'), ('manual', 'Ruční'), ('sheets_import', 'Sheets import')], default='manual', max_length=20)),
                ('fio_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('popis', models.CharField(blank=True, default='', max_length=500)),
                ('protiucet', models.CharField(blank=True, default='', max_length=64)),
                ('vs', models.CharField(blank=True, default='', max_length=32)),
                ('zprava', models.TextField(blank=True, default='')),
                ('ignorovat', models.BooleanField(default=False)),
                ('zarazeno_automaticky', models.BooleanField(default=False)),
                ('poznamka_admin', models.TextField(blank=True, default='')),
                ('upravil_user_id', models.IntegerField(blank=True, null=True)),
                ('upraveno', users.fields.SafeDateTimeField(blank=True, null=True)),
                ('vytvoreno', users.fields.SafeDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Položka nákladu',
                'verbose_name_plural': 'Položky nákladů',
                'db_table': 'finance_naklad_polozka',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PacketaProvizePolozka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodejna_id', models.IntegerField()),
                ('cas', models.DateTimeField()),
                ('zasilka', models.CharField(max_length=64)),
                ('zasilka_raw', models.CharField(blank=True, default='', max_length=80)),
                ('typ_provize', models.CharField(max_length=120)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mena', models.CharField(default='Kč', max_length=8)),
                ('poznamka', models.CharField(blank=True, default='', max_length=200)),
                ('import_batch', models.CharField(max_length=64)),
                ('vytvoreno', users.fields.SafeDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Packeta provize',
                'verbose_name_plural': 'Packeta provize položky',
                'db_table': 'finance_packeta_provize',
                'ordering': ['-cas'],
                'indexes': [models.Index(fields=['prodejna_id', 'cas'], name='finance_pac_prodejn_124458_idx'), models.Index(fields=['zasilka'], name='finance_pac_zasilka_137992_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='packetaprovizepolozka',
            constraint=models.UniqueConstraint(fields=('prodejna_id', 'zasilka', 'typ_provize', 'cas'), name='finance_packeta_uniq_row'),
        ),
        migrations.AddField(
            model_name='nakladpolozka',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polozky', to='finance.nakladkategorie'),
        ),
        migrations.AddField(
            model_name='fiokategorizacnipravidlo',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fio_pravidla', to='finance.nakladkategorie'),
        ),
        migrations.AddIndex(
            model_name='nakladpolozka',
            index=models.Index(fields=['stav', 'datum'], name='finance_nak_stav_d02080_idx'),
        ),
        migrations.AddIndex(
            model_name='nakladpolozka',
            index=models.Index(fields=['rok', 'mesic'], name='finance_nak_rok_41819c_idx'),
        ),
    ]
