# Generated by Django 4.2.23 on 2026-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDutyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True, default='', verbose_name='Popis')),
                ('periodicity', models.CharField(choices=[('daily', 'Denně'), ('shift', 'Po směně'), ('weekly', 'Týdně')], default='daily', max_length=20)),
                ('store', models.CharField(blank=True, default='', max_length=100, verbose_name='Prodejna')),
                ('role', models.CharField(blank=True, default='', max_length=50, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Denní povinnost',
                'verbose_name_plural': 'Denní povinnosti',
                'db_table': 'WEB_DENNI_POVINNOSTI',
                'ordering': ['store', 'title'],
            },
        ),
    ]
