# Generated by Django 4.2.23 on 2026-10-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_app_activity_log'),
        ('stores', '0006_enable_servis_all_stores'),
        ('daily_duties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydutytemplate',
            options={'ordering': ['title'], 'verbose_name': 'Denní povinnost', 'verbose_name_plural': 'Denní povinnosti'},
        ),
        migrations.AddField(
            model_name='dailydutytemplate',
            name='prodejna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_duty_templates', to='stores.prodejna', verbose_name='Prodejna'),
        ),
        migrations.AddField(
            model_name='dailydutytemplate',
            name='uzivatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_duty_templates', to='users.webuser', verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='dailydutytemplate',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Denně'), ('weekly', 'Týdně'), ('monthly', 'Měsíčně')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailydutytemplate',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Role (text)'),
        ),
        migrations.AlterField(
            model_name='dailydutytemplate',
            name='store',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prodejna (text)'),
        ),
        migrations.CreateModel(
            name='DailyDutyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Začátek období')),
                ('note', models.TextField(blank=True, default='', verbose_name='Poznámka')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_duty_completions', to='users.webuser')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='daily_duties.dailydutytemplate')),
            ],
            options={
                'verbose_name': 'Splnění povinnosti',
                'verbose_name_plural': 'Splnění povinností',
                'db_table': 'WEB_DENNI_POVINNOSTI_SPLNENI',
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailydutycompletion',
            constraint=models.UniqueConstraint(fields=('template', 'period_start'), name='daily_duty_one_completion_per_period'),
        ),
    ]
