# Generated by Django 4.2.23 on 2025-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodejna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název prodejny')),
                ('nazev_kratkiy', models.CharField(help_text='Pro zobrazení v tabulkách', max_length=20, verbose_name='Krátký název')),
                ('nazev_google_sheets', models.CharField(blank=True, help_text='Jak se prodejna jmenuje v Google tabulce', max_length=100, null=True, verbose_name='Název v Google Sheets')),
                ('adresa', models.TextField(blank=True, null=True, verbose_name='Adresa')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('otevreno_od', models.TimeField(blank=True, null=True, verbose_name='Otevřeno od')),
                ('otevreno_do', models.TimeField(blank=True, null=True, verbose_name='Otevřeno do')),
                ('vedouci_prodejny', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vedoucí prodejny')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('barva', models.CharField(default='#0066cc', help_text='Pro rozlišení v grafech a UI', max_length=7, verbose_name='Barva (hex kód)')),
                ('poradi', models.IntegerField(default=0, help_text='Pro řazení v seznamech', verbose_name='Pořadí')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('datum_upravy', models.DateTimeField(auto_now=True, verbose_name='Datum úpravy')),
            ],
            options={
                'verbose_name': 'Prodejna',
                'verbose_name_plural': 'Prodejny',
                'db_table': 'WEB_PRODEJNY',
                'ordering': ['poradi', 'nazev'],
            },
        ),
    ]
