# Generated by Django 4.2.23 on 2026-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_prodejna_povolena_pozice_servis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodejna',
            name='vedouci_prodejny',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vedoucí prodejny (legacy text)'),
        ),
    ]
