# Generated by Django 4.2.23 on 2025-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WEB_PRISTUPY_PRODEJNY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='Název společnosti')),
                ('website_url', models.URLField(max_length=500, verbose_name='URL adresa')),
                ('username', models.CharField(max_length=100, verbose_name='Uživatelské jméno')),
                ('password', models.CharField(max_length=255, verbose_name='Heslo')),
                ('category', models.CharField(blank=True, help_text='Kategorie přístupu (např. Dodavatel, E-shop, Admin, atd.)', max_length=50, null=True, verbose_name='Kategorie')),
                ('store', models.CharField(max_length=100, verbose_name='Prodejna')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Poznámky')),
                ('added_by', models.CharField(max_length=100, verbose_name='Přidal uživatel')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Poslední použití')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Přístup prodejny',
                'verbose_name_plural': 'Přístupy prodejen',
                'db_table': 'WEB_PRISTUPY_PRODEJNY',
                'ordering': ['store', 'company_name'],
            },
        ),
    ]
