# Generated by Django 4.2.23 on 2025-07-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_webuser_adresa_webuser_email_webuser_poznamka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodejna', models.CharField(choices=[('Globus', 'Globus'), ('Senimo', 'Senimo'), ('Zlín', 'Zlín'), ('Přerov', 'Přerov'), ('Vsetín', 'Vsetín'), ('Šternberk', 'Šternberk')], max_length=50)),
                ('datum', models.DateField()),
                ('cas_od', models.TimeField()),
                ('cas_do', models.TimeField()),
                ('typ_smeny', models.CharField(choices=[('prace', 'Práce'), ('dovolena', 'Dovolená'), ('nemoc', 'Nemocenská')], default='prace', max_length=20)),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('aktivni', models.BooleanField(default=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smeny', to='users.webuser')),
            ],
            options={
                'verbose_name': 'Směna',
                'verbose_name_plural': 'Směny',
                'db_table': 'WEB_SMENY',
                'ordering': ['-datum', 'cas_od'],
                'unique_together': {('user', 'datum', 'prodejna')},
            },
        ),
        migrations.CreateModel(
            name='SmenaDochazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_akce', models.CharField(choices=[('prichod', 'Příchod'), ('odchod', 'Odchod'), ('pauza_start', 'Začátek pauzy'), ('pauza_konec', 'Konec pauzy')], max_length=20)),
                ('cas', models.DateTimeField()),
                ('poznamka', models.TextField(blank=True, null=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('smena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dochazka', to='shifts.smena')),
            ],
            options={
                'verbose_name': 'Docházka',
                'verbose_name_plural': 'Docházka',
                'db_table': 'WEB_SMENY_DOCHAZKA',
                'ordering': ['cas'],
            },
        ),
        migrations.CreateModel(
            name='SmenaStatistiky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesic', models.DateField()),
                ('pocet_hodin_naplanovanych', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pocet_hodin_odpracovanych', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pocet_hodin_dovolene', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pocet_hodin_pauz', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pocet_presasu', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('posledni_aktualizace', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smena_statistiky', to='users.webuser')),
            ],
            options={
                'verbose_name': 'Statistiky směn',
                'verbose_name_plural': 'Statistiky směn',
                'db_table': 'WEB_SMENY_STATISTIKY',
                'ordering': ['-mesic'],
                'unique_together': {('user', 'mesic')},
            },
        ),
    ]
