# Generated by Django 4.2.23 on 2025-08-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('shifts', '0004_finalize_prodejna_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smena',
            name='prodejna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='smeny', to='stores.prodejna', verbose_name='Prodejna'),
            preserve_default=False,
        ),
    ]
