# Generated by Django 4.2.23 on 2026-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_smena_pozice_smeny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mzdovapenalizacemesic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
