# Generated by Django 4.2.23 on 2026-07-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamacePolozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nase_znacka', models.CharField(max_length=20, verbose_name='Naše značka')),
                ('jejich_oznaceni', models.CharField(blank=True, default='', max_length=100, verbose_name='Jejich označení')),
                ('nazev_zbozi', models.CharField(max_length=300, verbose_name='Název zboží')),
                ('dodavatel', models.CharField(blank=True, default='', max_length=100, verbose_name='Dodavatel')),
                ('faktura', models.CharField(blank=True, default='', max_length=50, verbose_name='Faktura')),
                ('ean', models.CharField(blank=True, default='', max_length=50, verbose_name='EAN')),
                ('p_kod', models.CharField(blank=True, default='', max_length=50, verbose_name='P kód')),
                ('datum_odeslani', models.DateField(blank=True, null=True, verbose_name='Datum odeslání')),
                ('cislo_zasilky', models.CharField(blank=True, default='', max_length=100, verbose_name='Číslo zásilky')),
                ('poznamka', models.TextField(blank=True, default='', verbose_name='Poznámka')),
                ('prodejna', models.CharField(max_length=100, verbose_name='Prodejna')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reklamace položka',
                'verbose_name_plural': 'Reklamace evidence',
                'db_table': 'WEB_REKLAMACE_EVIDENCE',
                'ordering': ['-datum_odeslani', '-nase_znacka'],
            },
        ),
    ]
