# Generated by Django 4.2.23 on 2025-07-20 14:50

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obsah', models.TextField(verbose_name='Obsah komentáře')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('datum_upravy', models.DateTimeField(auto_now=True, verbose_name='Datum úpravy')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='users.webuser')),
            ],
            options={
                'verbose_name': 'Komentář',
                'verbose_name_plural': 'Komentáře',
                'db_table': 'WEB_NOVINKY_KOMENTARE',
                'ordering': ['datum_vytvoreni'],
            },
        ),
        migrations.CreateModel(
            name='Novinka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obsah', models.TextField(verbose_name='Obsah příspěvku')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('datum_upravy', models.DateTimeField(auto_now=True, verbose_name='Datum úpravy')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novinky', to='users.webuser')),
            ],
            options={
                'verbose_name': 'Novinka',
                'verbose_name_plural': 'Novinky',
                'db_table': 'WEB_NOVINKY',
                'ordering': ['-datum_vytvoreni'],
            },
        ),
        migrations.CreateModel(
            name='NovinkaSoubor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soubor', models.FileField(upload_to=news.models.get_file_path, verbose_name='Soubor')),
                ('nazev', models.CharField(max_length=255, verbose_name='Název souboru')),
                ('typ', models.CharField(choices=[('obrazek', 'Obrázek'), ('dokument', 'Dokument'), ('video', 'Video'), ('audio', 'Audio'), ('jiny', 'Jiný')], default='jiny', max_length=20, verbose_name='Typ souboru')),
                ('velikost', models.IntegerField(verbose_name='Velikost v bytech')),
                ('datum_nahrani', models.DateTimeField(auto_now_add=True, verbose_name='Datum nahrání')),
                ('novinka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soubory', to='news.novinka')),
            ],
            options={
                'verbose_name': 'Soubor novinky',
                'verbose_name_plural': 'Soubory novinek',
                'db_table': 'WEB_NOVINKY_SOUBORY',
            },
        ),
        migrations.CreateModel(
            name='KomentarSoubor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soubor', models.FileField(upload_to=news.models.get_file_path, verbose_name='Soubor')),
                ('nazev', models.CharField(max_length=255, verbose_name='Název souboru')),
                ('typ', models.CharField(choices=[('obrazek', 'Obrázek'), ('dokument', 'Dokument'), ('video', 'Video'), ('audio', 'Audio'), ('jiny', 'Jiný')], default='jiny', max_length=20, verbose_name='Typ souboru')),
                ('velikost', models.IntegerField(verbose_name='Velikost v bytech')),
                ('datum_nahrani', models.DateTimeField(auto_now_add=True, verbose_name='Datum nahrání')),
                ('komentar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soubory', to='news.komentar')),
            ],
            options={
                'verbose_name': 'Soubor komentáře',
                'verbose_name_plural': 'Soubory komentářů',
                'db_table': 'WEB_NOVINKY_KOMENTARE_SOUBORY',
            },
        ),
        migrations.AddField(
            model_name='komentar',
            name='novinka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='news.novinka'),
        ),
        migrations.CreateModel(
            name='Reakce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('like', '👍 Like'), ('dislike', '👎 Dislike'), ('srdce', '❤️ Srdce'), ('smich', '😂 Smích'), ('smutek', '😢 Smutek'), ('hnev', '😠 Hněv'), ('prekvapeni', '😮 Překvapení')], default='like', max_length=20, verbose_name='Typ reakce')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('novinka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reakce', to='news.novinka')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reakce', to='users.webuser')),
            ],
            options={
                'verbose_name': 'Reakce',
                'verbose_name_plural': 'Reakce',
                'db_table': 'WEB_NOVINKY_REAKCE',
                'unique_together': {('novinka', 'uzivatel')},
            },
        ),
    ]
