# Generated by Django 4.2.23 on 2025-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název kategorie')),
                ('barva', models.CharField(default='#0066cc', max_length=7, verbose_name='Barva kategorie (hex)')),
                ('ikona', models.CharField(blank=True, max_length=50, verbose_name='CSS ikona')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'db_table': 'WEB_NOVINKY_KATEGORIE',
                'ordering': ['nazev'],
            },
        ),
        migrations.AddField(
            model_name='novinka',
            name='kategorie',
            field=models.ManyToManyField(blank=True, related_name='novinky', to='news.kategorie', verbose_name='Kategorie'),
        ),
    ]
