# Generated by Django 4.2.23 on 2025-07-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_kategorie_novinka_kategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovinkaKategorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.kategorie')),
                ('novinka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.novinka')),
            ],
            options={
                'db_table': 'WEB_NOVINKY_KATEGORIE_M2M',
                'unique_together': {('novinka', 'kategorie')},
            },
        ),
        migrations.AlterField(
            model_name='novinka',
            name='kategorie',
            field=models.ManyToManyField(blank=True, related_name='novinky', through='news.NovinkaKategorie', to='news.kategorie', verbose_name='Kategorie'),
        ),
    ]
