# Generated by Django 4.2.23 on 2026-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_novinkakategorie_alter_novinka_kategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUserVisitState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='USER_ID', unique=True)),
                ('last_seen_at', models.DateTimeField(db_column='LAST_SEEN_AT')),
            ],
            options={
                'verbose_name': 'Návštěva novinek',
                'verbose_name_plural': 'Návštěvy novinek',
                'db_table': 'WEB_NOVINKY_USER_VISIT',
            },
        ),
    ]
