# Generated by Django 4.2.23 on 2025-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uzivatelske_jmeno', models.CharField(default='temp', max_length=50, unique=True, verbose_name='Uživatelské jméno')),
                ('jmeno', models.CharField(max_length=50, verbose_name='Jméno')),
                ('prijmeni', models.CharField(default='', max_length=50, verbose_name='Příjmení')),
                ('heslo', models.CharField(max_length=255, verbose_name='Heslo')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrátor'), ('PRODEJCE', 'Prodejce')], default='PRODEJCE', max_length=20, verbose_name='Role')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('moduly', models.JSONField(default=list, verbose_name='Povolené moduly')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('datum_upravy', models.DateTimeField(auto_now=True, verbose_name='Datum úpravy')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Poslední přihlášení')),
            ],
            options={
                'verbose_name': 'Uživatel',
                'verbose_name_plural': 'Uživatelé',
                'db_table': 'WEB_USERS',
            },
        ),
    ]
