# Generated by Django 4.2.23 on 2025-07-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='adresa',
            field=models.TextField(blank=True, null=True, verbose_name='Adresa'),
        ),
        migrations.AddField(
            model_name='webuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='webuser',
            name='poznamka',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='webuser',
            name='prodejna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prodejna'),
        ),
        migrations.AddField(
            model_name='webuser',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonní číslo'),
        ),
        migrations.CreateModel(
            name='ProfilovyObrazek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.ImageField(upload_to='profilove_obrazky/', verbose_name='Profilový obrázek')),
                ('datum_nahrani', models.DateTimeField(auto_now_add=True, verbose_name='Datum nahrání')),
                ('uzivatel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilovy_obrazek', to='users.webuser', verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Profilový obrázek',
                'verbose_name_plural': 'Profilové obrázky',
                'db_table': 'WEB_PROFILOVE_OBRAZKY',
            },
        ),
    ]
