# Generated by Django 4.2.23 on 2025-07-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0005_finalize_prodejna_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='prodejna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzivatele', to='stores.prodejna', verbose_name='Prodejna'),
        ),
    ]
