# Generated by Django 4.2.23 on 2025-07-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_webuser_prodejna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webuser',
            name='prodejna',
        ),
    ]
