# Generated by Django 4.2.23 on 2025-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_webuser_prodejna'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='prodejna_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID domovské prodejny'),
        ),
    ]
