# Generated by Django 4.2.26 on 2026-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_populate_technik_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webuser',
            name='datum_upravy',
        ),
        migrations.AlterField(
            model_name='webuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrátor'), ('VEDOUCI', 'Vedoucí'), ('PRODEJCE', 'Prodejce')], default='PRODEJCE', max_length=20, verbose_name='Role'),
        ),
    ]
