# Generated by Django 4.2.23 on 2026-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_webuser_servis_uroven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='mzda_zaklad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixní body (prodejce) / body za hodinu (brigádník)'),
        ),
    ]
